'use client';
import Link from 'next/link';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ArrowLeft,Check,ChevronRight,Clock3,FileText,RefreshCw,Upload,Wallet } from 'lucide-react';
import { STAGES,cents } from '../../lib/expense-ledger.mjs';
import './people-workbench.css';
import { WeeklyPanel,DisputesPanel,type Workflow } from './workflow-panel';

type Claim={stage:string;project_name:string;approval_id:string;expected_date:string;submitted_date:string;received_date:string;reimbursed_cents:number;reference:string;note:string;handler:string;confirmation_status:string;confirmed_at:string;confirmed_by:string;confirmation_note:string;updated_by?:string;updated_at?:string};
type Transaction={id:string;order_no:string;merchant_order_no:string;person_id:string;kind:string;amount_cents:number;occurred_at:string;description:string;payment_method:string;trade_status:string;source_json:string;source_line:number};
type RecordRow=Transaction&{netCents:number;refundCents:number;refunds:Transaction[];claim:Claim;confirmed:boolean;completed:boolean;overdue:boolean;anomaly:boolean};
type Person={id:string;bill_name:string;member_id:string|null;member_name:string|null;netCents:number;grossCents:number;refundCents:number;reimbursedCents:number;exemptCents:number;unconfirmedCount:number;overdueCount:number;openCount:number;missingDateCount:number;expectedDate:string;paymentCount:number;disputedCount:number;unmatchedRefundCount:number};
type Approval={id:string;title:string;project:string;status:string;current_step:string;current_reviewer_name:string;requester_name:string};
type Work={id:string;title:string;project:string;status:string;step:string;reviewer:string;updatedAt:string;work:string;hours:number|null;ratio:number|null;accepted:boolean};
type Labor=Omit<Work,'work'|'hours'|'ratio'|'accepted'>&{month:string;statement:string;contributionHours:number|null;otherHours:number|null;totalHours:number|null;suggestedCents:number|null;approvedCents:number|null;paidCents:number|null;remainingCents:number|null;paidDate:string;reference:string;basis:string};
type Profile={id:string;name:string;role:string;billPersonId:string;work:Work[];labor:Labor[];purchases:Work[];acceptedHours:number|null;acceptedWorkCount:number};
type EventRow={id:string;target_id:string;action:string;actor:string;occurred_at:string;after_json:string};
type Overview={workflow:Workflow;revision:number;manager:boolean;memberId:string;people:Person[];records:RecordRow[];unmatchedRefunds:Transaction[];members:{id:string;full_name:string}[];approvals:Approval[];events:EventRow[];profiles:Profile[]};
type Preview={newCount:number;duplicateCount:number;selectedCount:number;ignoredCount:number};
type Tab='work'|'expenses'|'pay';
const money=(n:number|null|undefined)=>n==null?'待核对':'¥'+(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const stage=(r:RecordRow)=>r.anomaly?'金额待核对':r.claim.confirmation_status==='disputed'?'本人提出异议':!r.confirmed?'待本人确认':r.netCents===0?'已全额退款':STAGES[r.claim.stage]||'待填写';
const endpoint='/api/expense-ledger';
const editableKeys=['stage','project_name','approval_id','expected_date','submitted_date','received_date','reimbursed_cents','reference','note','handler'] as const;
async function api(body?:object){const response=await fetch(endpoint,{credentials:'same-origin',cache:'no-store',method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json() as Overview&{error?:string;preview:Preview};if(!response.ok)throw new Error(data.error||'读取失败，请重试。');return data;}

export default function PeopleWorkbench(){
  const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [profileId,setProfileId]=useState(''),[tab,setTab]=useState<Tab>('expenses'),[search,setSearch]=useState(''),[month,setMonth]=useState(''),[filter,setFilter]=useState('all');
  const [detailId,setDetailId]=useState(''),[selected,setSelected]=useState<string[]>([]),[importFile,setImportFile]=useState<{filename:string;csv:string;preview:Preview}|null>(null);
  const refresh=useCallback(async()=>{try{const next=await api() as Overview;setData(next);setError('');return next;}catch(e){setError(e instanceof Error?e.message:'加载失败');throw e;}},[]);
  useEffect(()=>{let active=true;void api().then((next:Overview)=>{if(!active)return;setData(next);const params=new URLSearchParams(window.location.search);const target=params.get('person')||(!next.manager?next.profiles[0]?.id:'');setProfileId(target||'');const t=params.get('tab');if(t==='work'||t==='pay'||t==='expenses')setTab(t);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'加载失败');});return()=>{active=false;};},[]);
  const run=async(body:object,success:string)=>{if(!data||busy)return;setBusy(true);setError('');setNotice('');try{await api({...body,revision:data.revision});await refresh();setNotice(success);setSelected([]);return true;}catch(e){setError(e instanceof Error?e.message:'保存失败');return false;}finally{setBusy(false);}};
  const choose=(id:string)=>{setProfileId(id);setSelected([]);setDetailId('');setMonth('');setFilter('all');window.history.replaceState(null,'',id?'?person='+encodeURIComponent(id)+'&tab='+tab:window.location.pathname);};
  const profile=data?.profiles.find(p=>p.id===profileId),person=data?.people.find(p=>p.id===profile?.billPersonId);
  const records=data?.records.filter(r=>r.person_id===person?.id)||[];
  const rows=records.filter(r=>(!month||r.occurred_at.startsWith(month))&&(filter==='all'||(filter==='disputed'&&r.claim.confirmation_status==='disputed')||(filter==='pending'&&!r.confirmed)||(filter==='open'&&!r.completed)||(filter==='overdue'&&r.overdue)||(filter==='done'&&r.completed)));
  const detail=records.find(r=>r.id===detailId),isSelf=Boolean(person?.member_id&&person.member_id===data?.memberId);
  const people=useMemo(()=>data?.profiles.filter(p=>p.name.includes(search)).sort((a,b)=>Number(Boolean(b.billPersonId))-Number(Boolean(a.billPersonId))||a.name.localeCompare(b.name,'zh-CN'))||[],[data,search]);
  const upload=async(file:File|undefined)=>{if(!file||!data)return;if(file.size>2_000_000){setError('单个账单最大为 2 MB。');return;}setBusy(true);setError('');try{const buffer=await file.arrayBuffer();let csv;try{csv=new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{csv=new TextDecoder('gb18030',{fatal:true}).decode(buffer);}const result=await api({action:'preview',csv,filename:file.name,revision:data.revision});setImportFile({filename:file.name,csv,preview:result.preview});}catch(e){setError(e instanceof Error?e.message:'无法读取账单。');}finally{setBusy(false);}};
  const exportRows=()=>{const list=rows.flatMap(r=>[r,...r.refunds]);const keys=['交易时间','交易分类','交易对方','商品说明','收/支','金额','交易订单号','商家订单号'];const escape=(value:string)=>'"'+(/^[=+\-@]/.test(value)?"'":'')+value.replaceAll('"','""')+'"';const csv='\uFEFF'+[keys,...list.map(r=>{const raw=JSON.parse(r.source_json);return keys.map(k=>String(raw[k]||''));})].map(r=>r.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=(profile?.name||'本人')+'-消费明细.csv';a.click();URL.revokeObjectURL(url);};
  return <main className="pw"><header className="pw-top"><Link href="/"><ArrowLeft size={17}/>联合研发 OA</Link><span>人员工作台</span><button disabled={busy} onClick={()=>void refresh().catch(()=>{})}><RefreshCw size={16}/>刷新</button></header>
    <div className="pw-intro"><div><p className="pw-kicker">工作有记录 · 花费可核对 · 报酬有依据</p><h1>{profile?profile.name+'的主页':'人员工作台'}</h1><p>{profile?'工作与成果、消费与报销、绩效与报酬集中查看。':'点一个人，查看工作、消费报销和应发报酬。'}</p></div>{data?.manager&&<label className="pw-upload"><Upload size={17}/>导入支付宝账单<input disabled={busy} type="file" accept=".csv" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label>}</div>
    {error&&<p className="pw-error" role="alert">{error}</p>}{notice&&<p className="pw-notice" role="status">{notice}</p>}
    {importFile&&<section className="pw-import"><h2>确认导入</h2><p>{importFile.filename}</p><p>本次识别 {importFile.preview.selectedCount} 条，新增 {importFile.preview.newCount} 条，重复 {importFile.preview.duplicateCount} 条。其余 {importFile.preview.ignoredCount} 条不属于已登记人员，本次不导入。</p><p>新增消费将等待本人确认，已有报销进度保留。</p><button className="pw-primary" disabled={busy} onClick={async()=>{if(await run({action:'import',csv:importFile.csv,filename:importFile.filename},'已导入，新增消费等待本人确认。'))setImportFile(null);}}>导入账单</button><button disabled={busy} onClick={()=>setImportFile(null)}>取消</button></section>}
    {data&&<DisputesPanel workflow={data.workflow} busy={busy} run={run} onOpen={d=>{const p=data.profiles.find(p=>p.id===d.member_id);if(p){choose(p.id);setTab(d.target_type==='work'?'work':'expenses');if(d.target_type==='expense')setDetailId(d.target_id);}}}/>}
    {!data?<p className="pw-empty">{error?'登录 OA 后可查看本人的人员主页。':'正在读取人员与账单…'}</p>:!profile?<><div className="pw-toolbar"><input aria-label="搜索人员" placeholder="搜索姓名" value={search} onChange={e=>setSearch(e.target.value)}/><span>{people.length} 位成员</span></div><div className="pw-people">{people.map(p=>{const bill=data.people.find(x=>x.id===p.billPersonId);return <button className="pw-person" key={p.id} onClick={()=>choose(p.id)}><div className="pw-person-head"><span className="pw-avatar">{p.name.slice(-2)}</span><h2>{p.name}</h2><ChevronRight size={18}/></div><dl><div><dt>工作成果</dt><dd>{p.work.length+data.workflow.weekly.filter(w=>w.member_id===p.id).length} 项 · 已通过 {p.acceptedWorkCount+data.workflow.weekly.filter(w=>w.member_id===p.id&&w.accepted).length}</dd></div><div><dt>消费净额</dt><dd>{bill?money(bill.netCents):'暂无已导入账单'}</dd></div><div><dt>绩效报酬</dt><dd>{p.labor.length?p.labor.length+' 份申请':'待申报／待核定'}</dd></div></dl>{bill&&<p className="pw-card-status">{!bill.member_id?'待关联 OA 账号':bill.unconfirmedCount?'待本人确认 '+bill.unconfirmedCount+' 笔':bill.openCount?'报销跟进 '+bill.openCount+' 笔':'已完成'}{bill.overdueCount>0&&' · 逾期 '+bill.overdueCount+' 笔'}</p>}</button>;})}</div></>:<>
      <div className="pw-profile-nav"><button onClick={()=>choose('')}><ArrowLeft size={15}/>人员列表</button><span>{person?'支付宝姓名：'+person.bill_name:'OA 成员主页'}</span></div>
      <div className="pw-tabs" role="tablist" aria-label="人员主页栏目">{([['work','工作与成果'],['expenses','消费与报销'],['pay','绩效与报酬']] as [Tab,string][]).map(([key,label],i)=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key);window.history.replaceState(null,'','?person='+encodeURIComponent(profileId)+'&tab='+key);}}><span>0{i+1}</span>{label}</button>)}</div>
      {tab==='work'&&<WeeklyPanel key={profile.id+'-'+data.revision} workflow={data.workflow} memberId={profile.id} own={profile.id===data.memberId} manager={data.manager} busy={busy} run={run}/>}
      {tab==='work'&&<section className="pw-panel"><div className="pw-section-title"><h2>工作记录与验收</h2><Link href="/">前往 OA 登记成果</Link></div><p>已归档成果 {profile.acceptedWorkCount} 项，已核实的折算贡献工时 {profile.acceptedHours==null?'待关联账号':profile.acceptedHours.toFixed(2)+' 小时'}。</p>{profile.work.length?profile.work.map(w=><article className="pw-work" key={w.id}><div><h3>{w.title}</h3><span className="pw-badge">{w.status}</span></div><p>{w.work||'尚未填写本人的具体工作说明'}</p><dl><div><dt>归属项目</dt><dd>{w.project}</dd></div><div><dt>当前环节</dt><dd>{w.step} · {w.reviewer||'待分配'}</dd></div><div><dt>贡献依据</dt><dd>{w.ratio==null?'待核定':w.ratio+'%'} · {w.hours==null?'工时待核定':w.hours.toFixed(2)+' 小时'}</dd></div></dl><small>申请编号：{w.id}</small><Link href={'/?approval='+encodeURIComponent(w.id)}>查看原审批</Link></article>):<p className="pw-empty">{profile.role==='unlinked'?'关联 OA 账号后显示该成员的工作记录。':'暂未找到已登记的技术工作。请本人在 OA 提交实际工作与成果。'}</p>}</section>}
      {tab==='expenses'&&<>
        {!person?<section className="pw-panel pw-empty">暂无此人的已导入消费账单。</section>:<>
        {data.manager&&<div className="pw-binding"><label>关联 OA 本人账号 <select aria-label="关联 OA 本人账号" value={person.member_id||''} disabled={busy} onChange={e=>void run({action:'bind',personId:person.id,memberId:e.target.value},'账号关联已更新，请本人确认消费。')}><option value="">待关联</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><span>由关联账号本人确认，管理员不能代替本人确认。</span></div>}
        <div className="pw-metrics"><Metric label="消费净额" value={money(person.netCents)} note={'付款 '+money(person.grossCents)+'，退款 '+money(person.refundCents)}/><Metric label="已报销到账" value={money(person.reimbursedCents)} note="仅计已登记的到账金额"/><Metric label="尚待核实／报销" value={money(Math.max(0,person.netCents-person.reimbursedCents-person.exemptCents))} note={'无需报销 '+money(person.exemptCents)}/><Metric label="预计全部报完" value={person.openCount===0?'已完成':person.expectedDate||'待本人补充'} note={person.missingDateCount?person.missingDateCount+' 笔未填预计日期':'以各笔预计完成日期为准'}/></div>
        <div className="pw-attention"><Clock3 size={18}/><span>待本人确认 {person.unconfirmedCount} 笔 · 有异议 {person.disputedCount} 笔 · 逾期 {person.overdueCount} 笔</span></div>
        <div className="pw-toolbar"><label>消费月份 <input type="month" value={month} onChange={e=>{setMonth(e.target.value);setSelected([]);}}/></label><select aria-label="报销状态筛选" value={filter} onChange={e=>{setFilter(e.target.value);setSelected([]);}}><option value="all">全部记录</option><option value="pending">待本人确认</option><option value="disputed">有异议</option><option value="open">尚未报完</option><option value="overdue">已逾期</option><option value="done">已完成</option></select><button onClick={exportRows} disabled={!rows.length}>导出当前明细</button></div>
        {isSelf&&<div className="pw-confirm-bar"><label><input type="checkbox" checked={rows.some(r=>!r.confirmed&&!r.anomaly&&r.claim.confirmation_status!=='disputed'&&r.claim.confirmation_status!=='disputed')&&rows.filter(r=>!r.confirmed&&!r.anomaly&&r.claim.confirmation_status!=='disputed').every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?rows.filter(r=>!r.confirmed&&!r.anomaly&&r.claim.confirmation_status!=='disputed').map(r=>r.id):[])}/>选择当前待确认记录</label><button className="pw-primary" disabled={busy||!selected.length} onClick={()=>void run({action:'confirm',ids:selected},'已确认消费归属，后续报销由你跟进。')}><Check size={16}/>确认选中 {selected.length} 笔属于我，由我跟进报销</button></div>}
        <section className="pw-panel"><div className="pw-section-title"><h2>消费明细</h2><span>{rows.length} 笔付款</span></div><div className="pw-records">{rows.map(r=><article className={'pw-record '+(r.overdue?'overdue':'')} key={r.id}>{isSelf&&!r.confirmed&&<input aria-label={'选择 '+r.occurred_at+' 的消费'} type="checkbox" disabled={r.anomaly||r.claim.confirmation_status==='disputed'} checked={selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(id=>id!==r.id))}/>}<button onClick={()=>setDetailId(r.id)}><div><strong>{r.description}</strong><span className="pw-badge">{stage(r)}</span></div><div className="pw-record-meta"><span>{r.occurred_at}</span><span>{r.claim.project_name||'项目待对应'}</span></div><div className="pw-record-bottom"><b>{money(r.netCents)}</b><span>{r.refundCents>0?'已退 '+money(r.refundCents)+' · ':''}{r.claim.expected_date?'预计 '+r.claim.expected_date:'预计完成日期待补充'}</span><ChevronRight size={16}/></div></button></article>)}{!rows.length&&<p className="pw-empty">当前筛选没有记录。</p>}</div></section>
        {data.unmatchedRefunds.some(r=>r.person_id===person.id)&&<section className="pw-error">存在退款尚未对应到原付款；人员净额已扣除退款，逐笔报销金额需管理员核对原订单。</section>}
        </>}
        <section className="pw-panel"><h2>关联人员的采购申请</h2>{profile.purchases.length?profile.purchases.map(p=><div className="pw-purchase" key={p.id}><Link href={'/?approval='+encodeURIComponent(p.id)}>{p.title}</Link><span>{p.status} · {p.step} · {p.reviewer||'待分配'}</span></div>):<p className="pw-empty">暂无本人发起的采购申请。</p>}</section>
      </>}
      {tab==='pay'&&<section className="pw-panel"><div className="pw-section-title"><h2>绩效依据与劳务报酬</h2><Link href="/">前往 OA 申报／审核</Link></div><p>贡献工时作为核算依据；项目负责人提出金额，经费负责人终审，实际发放另行登记。</p>{profile.labor.length?profile.labor.map(l=><LaborCard key={l.id+'-'+data.revision} labor={l} manager={data.manager} busy={busy} onSave={body=>run(body,'发放记录已保存。')}/>):<div className="pw-empty"><Wallet size={26}/><h3>待申报／待核定</h3><p>尚无劳务报酬申请，暂不能确定应发金额。请本人关联已归档成果、填写月度工作和其他工时，再提交审核。</p></div>}</section>}
    </>}
    {detail&&data&&<RecordDetail key={detail.id+'-'+data.revision} row={detail} own={isSelf} ownerName={data.workflow.disputeOwnerName} error={error} approvals={data.approvals} events={data.events.filter(e=>e.target_id===detail.id)} busy={busy} onClose={()=>setDetailId('')} onSave={body=>run(body,'记录已保存。')}/>}
  </main>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="pw-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;}
function RecordDetail({row:r,own,ownerName,error,approvals,events,busy,onClose,onSave}:{row:RecordRow;own:boolean;ownerName:string;error:string;approvals:Approval[];events:EventRow[];busy:boolean;onClose:()=>void;onSave:(body:object)=>Promise<boolean|undefined>}){
  const [form,setForm]=useState({...r.claim}),[paid,setPaid]=useState((r.claim.reimbursed_cents/100).toFixed(2)),[dispute,setDispute]=useState(''),[localError,setLocalError]=useState('');
  const change=(key:keyof Claim,value:string)=>setForm(s=>({...s,[key]:value}));
  useEffect(()=>{const focused=document.activeElement as HTMLElement|null;const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('.pw-dialog button:not(:disabled),.pw-dialog input:not(:disabled),.pw-dialog select:not(:disabled),.pw-dialog textarea:not(:disabled),.pw-dialog a[href],.pw-dialog summary')).filter(el=>el.getClientRects().length>0);const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',fn);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',fn);document.body.style.overflow=previous;focused?.focus();};},[onClose]);
  const approval=approvals.find(a=>a.id===form.approval_id);
  return <div className="pw-overlay"><section className="pw-dialog" role="dialog" aria-modal="true" aria-labelledby="bill-title"><header><div><span>账单与报销跟进</span><h2 id="bill-title">{r.description} · {money(r.netCents)}</h2></div><button autoFocus onClick={onClose} aria-label="关闭账单详情">关闭</button></header><div className="pw-dialog-body">
    <p>{r.occurred_at} · {stage(r)}</p>{error&&<p className="pw-error" role="alert">{error}</p>}<p>原付款 {money(r.amount_cents)}，退款 {money(r.refundCents)}。</p>
    {!r.confirmed&&<section className="pw-import"><h3>{r.claim.confirmation_status==='disputed'?'本人已提出异议':'等待消费本人确认'}</h3>{r.claim.confirmation_note&&<p>{r.claim.confirmation_note}</p>}{own?<><p>确认表示这笔消费属于你，后续由你负责票据整理和报销跟进。</p><button disabled={busy||r.anomaly||r.claim.confirmation_status==='disputed'} className="pw-primary" onClick={()=>void onSave({action:'confirm',ids:[r.id]})}>确认是我的消费，由我跟进</button><label>有异议请说明（转交 {ownerName} 处理）<textarea value={dispute} onChange={e=>setDispute(e.target.value)} maxLength={1000} placeholder="例如：这笔消费不属于我，或金额需要核对"/></label><button disabled={busy||!dispute.trim()||r.claim.confirmation_status==='disputed'} onClick={()=>void onSave({action:'dispute',ids:[r.id],note:dispute})}>提交异议</button></>:<p>管理员关联账号后，由对应成员登录确认。</p>}</section>}
    {r.confirmed&&<p className="pw-notice">本人已于 {new Date(r.claim.confirmed_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}确认，负责后续报销跟进。</p>}
    {r.confirmed&&own&&<details className="pw-source"><summary>对此账单提出异议</summary><p>提交后转交 {ownerName} 处理，暂停本笔确认与进度修改。</p><textarea aria-label="账单异议原因" value={dispute} maxLength={1000} onChange={e=>setDispute(e.target.value)}/><button disabled={busy||!dispute.trim()} onClick={()=>void onSave({action:'dispute',ids:[r.id],note:dispute})}>提交异议</button></details>}
    <form onSubmit={async e=>{e.preventDefault();setLocalError('');try{const claim=Object.fromEntries(editableKeys.map(k=>[k,k==='reimbursed_cents'?cents(paid):form[k]]));await onSave({action:'progress',id:r.id,claim});}catch(error){setLocalError(error instanceof Error?error.message:'金额不正确');}}}>
      <fieldset disabled={busy||!r.confirmed||r.anomaly}><legend>报销进度</legend><div className="pw-form-grid">
        <label>当前阶段<select value={form.stage} onChange={e=>change('stage',e.target.value)}>{Object.entries(STAGES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
        <label>预计报完日期<input type="date" value={form.expected_date} onChange={e=>change('expected_date',e.target.value)}/></label>
        <label>归属项目<input value={form.project_name} onChange={e=>change('project_name',e.target.value)} maxLength={200} placeholder="填写实际归属项目"/></label>
        <label>当前跟进人／环节<input value={form.handler} onChange={e=>change('handler',e.target.value)} maxLength={200} placeholder="例如：本人补发票／财务审核"/></label>
        <label className="pw-wide">关联 OA 申请<select value={form.approval_id} onChange={e=>{const a=approvals.find(x=>x.id===e.target.value);setForm(s=>({...s,approval_id:e.target.value,project_name:s.project_name||a?.project||''}));}}><option value="">尚未关联</option>{approvals.map(a=><option key={a.id} value={a.id}>{a.title} · {a.requester_name} · {a.status}</option>)}</select></label>
        {approval&&<p className="pw-wide">原审批：{approval.status} / {approval.current_step} / {approval.current_reviewer_name||'待分配'}。<Link href={'/?approval='+encodeURIComponent(approval.id)}>查看原申请</Link></p>}
        <label>实际提交日期<input type="date" value={form.submitted_date} onChange={e=>change('submitted_date',e.target.value)}/></label>
        <label>已报销到账金额（元）<input type="number" min="0" step="0.01" value={paid} onChange={e=>setPaid(e.target.value)}/></label>
        <label>最近到账日期<input type="date" value={form.received_date} onChange={e=>change('received_date',e.target.value)}/></label>
        <label>报销单号／到账依据<input value={form.reference} onChange={e=>change('reference',e.target.value)} maxLength={200}/></label>
        <label className="pw-wide">买了什么、缺什么材料、下一步做什么<textarea rows={3} value={form.note} onChange={e=>change('note',e.target.value)} maxLength={1500} placeholder="账单未提供商品明细时，请本人补充用途；有退回或无需报销时说明原因。"/></label>
      </div>{localError&&<p role="alert" className="pw-error">{localError}</p>}<button className="pw-primary" type="submit">保存报销进度</button></fieldset>
    </form>
    <details className="pw-source"><summary><FileText size={16}/>查看原始支付宝记录</summary>{[r,...r.refunds].map(t=><div key={t.id}><h3>{t.kind==='refund'?'退款记录':'付款记录'} · 原文件第 {t.source_line} 行</h3><dl>{Object.entries(JSON.parse(t.source_json) as Record<string,string>).filter(([k,v])=>k&&v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>)}</details>
    <details className="pw-source"><summary>确认与进度记录（{events.length}）</summary>{events.map(e=><div key={e.id}><strong>{e.actor} · {({confirm:'本人确认',dispute:'提出异议',progress:'更新报销进度',resolve_dispute:'处理异议，退回本人确认'} as Record<string,string>)[e.action]||e.action}</strong><p>{new Date(e.occurred_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p><p className="pw-work-text">{eventSummary(e.after_json)}</p></div>)}</details>
  </div></section></div>;
}
function LaborCard({labor:l,manager,busy,onSave}:{labor:Labor;manager:boolean;busy:boolean;onSave:(body:object)=>Promise<boolean|undefined>}){const [paid,setPaid]=useState(l.paidCents==null?'':(l.paidCents/100).toFixed(2)),[date,setDate]=useState(l.paidDate),[reference,setReference]=useState(l.reference),[error,setError]=useState('');return <article className="pw-work"><div><h3>{l.month} · {l.title}</h3><span className="pw-badge">{l.status}</span></div><p>{l.statement}</p><dl><div><dt>核算工时</dt><dd>{l.totalHours??'待核定'} 小时</dd></div><div><dt>建议金额</dt><dd>{money(l.suggestedCents)}</dd></div><div><dt>终审批准金额</dt><dd>{l.approvedCents===null?'待终审':money(l.approvedCents)}</dd></div><div><dt>已登记发放</dt><dd>{money(l.paidCents)}</dd></div><div><dt>尚应发放</dt><dd>{money(l.remainingCents)}</dd></div></dl><p>金额依据：{l.basis||'待项目负责人填写'}</p><p>当前环节：{l.step} · {l.reviewer||'—'} <Link href={'/?approval='+encodeURIComponent(l.id)}>查看原申请</Link></p>{manager&&l.approvedCents!==null&&<details><summary>登记实际发放</summary><p>仅登记已发生的付款，不会发起转账。填 0 表示已核对尚未发放。</p><label>累计已发放（元）<input type="number" step="0.01" value={paid} onChange={e=>setPaid(e.target.value)}/></label><label>最近发放日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>付款依据<input value={reference} onChange={e=>setReference(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>{try{setError('');void onSave({action:'labor_payment',id:l.id,paidCents:cents(paid),paidDate:date,reference});}catch(e){setError(e instanceof Error?e.message:'金额错误');}}}>保存发放记录</button></details>}</article>;}

function eventSummary(raw:string){const d=JSON.parse(raw);const labels:Record<string,string>={status:'确认状态',netCents:'确认净额',note:'说明',resolution:'处理意见',returnedToMember:'已退回本人',stage:'报销阶段',project_name:'归属项目',approval_id:'OA 申请编号',expected_date:'预计报完',submitted_date:'提交日期',received_date:'到账日期',reimbursed_cents:'已到账',reference:'依据',handler:'跟进人'};return Object.entries(d).filter(([k])=>labels[k]).map(([k,v])=>labels[k]+'：'+(k==='stage'?STAGES[String(v)]||v:['netCents','reimbursed_cents'].includes(k)?money(Number(v)):k==='status'?({confirmed:'本人确认',disputed:'有异议',pending:'待确认'} as Record<string,string>)[String(v)]||v:v===true?'是':v||'未填')).join('；');}
